-- ============================================================
-- 1.1 DATABASE & SCHEMA ARCHITECTURE
-- ============================================================

CREATE OR REPLACE DATABASE HOSPITAL_ANALYTICS;

-- Layer Schemas
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.RAW;           -- Bronze
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.INTERMEDIATE;   -- Silver
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.DW;             -- Gold (Data Warehouse)
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.MARTS;          -- Platinum
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.AUDIT;          -- Audit & Lineage
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.CONFIG;         -- Configuration
CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.STAGING;        -- Temp staging

-- Warehouses
CREATE OR REPLACE WAREHOUSE WH_HOSPITAL_INGEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'For data ingestion from S3';

CREATE OR REPLACE WAREHOUSE WH_HOSPITAL_TRANSFORM
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'For ELT transformations';

CREATE OR REPLACE WAREHOUSE WH_HOSPITAL_ANALYTICS
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'For BI/Analytics queries';

