-- ============================================================
-- 1.2 S3 EXTERNAL STAGE SETUP
-- ============================================================

CREATE OR REPLACE STORAGE INTEGRATION S3_HOSPITAL_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::role/snowflake-hospital-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://hospital-data-bucket/');

CREATE OR REPLACE STAGE HOSPITAL_ANALYTICS.RAW.STG_S3_HOSPITAL
    STORAGE_INTEGRATION = S3_HOSPITAL_INT
    URL = 's3://hospital-data-bucket/'
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
                   SKIP_HEADER = 1 NULL_IF = ('NULL', 'null', '', 'N/A')
                   ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

-- File Formats
CREATE OR REPLACE FILE FORMAT HOSPITAL_ANALYTICS.RAW.FF_CSV_HOSPITAL
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '', 'N/A', 'None')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    TRIM_SPACE = TRUE
    DATE_FORMAT = 'YYYY-MM-DD'
    TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE OR REPLACE FILE FORMAT HOSPITAL_ANALYTICS.RAW.FF_JSON_HOSPITAL
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE;

CREATE OR REPLACE FILE FORMAT HOSPITAL_ANALYTICS.RAW.FF_PARQUET_HOSPITAL
    TYPE = 'PARQUET'
    SNAPPY_COMPRESSION = TRUE;