SHOW TABLES;

select * from HOSPITAL_ANALYTICS.AUDIT.PIPE_EXECUTION_LOG;
SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.PIPELINE_EXECUTION_LOG;
SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.DATA_QUALITY_ERRORS;
SELECT * FROM AUDIT.EXCEPTION_LOG;
SELECT * FROM FILE_INGESTION_LOG;