SHOW TABLES;

SELECT * FROM FILE_INGESTION_LOG;
SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.PIPELINE_EXECUTION_LOG;
SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.DATA_QUALITY_ERRORS;
SELECT * FROM AUDIT.EXCEPTION_LOG;
