
-- ============================================================
-- 2. PIPE_EXECUTION_LOG
-- ============================================================


CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.PIPE_EXECUTION_LOG
(
  
    EXECUTION_ID          VARCHAR       DEFAULT UUID_STRING()    NOT NULL,
    PIPE_NAME             VARCHAR                                NOT NULL,
    PIPE_SCHEMA           VARCHAR                                NOT NULL,
    PIPE_DATABASE         VARCHAR                                NOT NULL,
    EXECUTION_STATUS      VARCHAR                                NOT NULL,  -- STARTED | SUCCESS | PARTIAL | FAILED | NO_FILES
    TARGET_TABLE          VARCHAR                                NOT NULL,
    BATCH_ID              VARCHAR,
    SOURCE_LOCATION       VARCHAR,                                          -- S3 path prefix
    FILES_SUBMITTED       NUMBER        DEFAULT 0,
    FILES_LOADED          NUMBER        DEFAULT 0,
    FILES_FAILED          NUMBER        DEFAULT 0,
    FILES_SKIPPED         NUMBER        DEFAULT 0,
    ROWS_PARSED           NUMBER        DEFAULT 0,
    ROWS_LOADED           NUMBER        DEFAULT 0,
    ROWS_ERRORS           NUMBER        DEFAULT 0,
    PIPE_RECEIVED_TIME    TIMESTAMP_NTZ,                                     -- when Snowpipe received SQS notification
    START_TIMESTAMP       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_TIMESTAMP         TIMESTAMP_NTZ,
    DURATION_SECONDS      NUMBER,
    LATENCY_SECONDS       NUMBER,                                              -- time from S3 upload to load complete
    ERROR_MESSAGE         VARCHAR,
    ERROR_COUNT           NUMBER        DEFAULT 0,
    DQ_ISSUES_COUNT       NUMBER        DEFAULT 0,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY            VARCHAR       DEFAULT CURRENT_USER(),
    WAREHOUSE_NAME        VARCHAR       DEFAULT CURRENT_WAREHOUSE(),

    CONSTRAINT PK_PIPE_EXEC PRIMARY KEY (EXECUTION_ID)
)
CLUSTER BY (PIPE_NAME, START_TIMESTAMP)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Tracks every Snowpipe execution run with status and row counts';

select * from HOSPITAL_ANALYTICS.AUDIT.PIPE_EXECUTION_LOG;

-- ============================================================
-- 2.1 MASTER AUDIT TABLE - Pipeline Execution Tracking
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.PIPELINE_EXECUTION_LOG (
    EXECUTION_ID        VARCHAR(50) DEFAULT UUID_STRING(),
    PIPELINE_NAME       VARCHAR(200) NOT NULL,
    LAYER_NAME          VARCHAR(50) NOT NULL,        -- RAW/INTERMEDIATE/DW/MARTS
    SOURCE_TABLE        VARCHAR(200),
    TARGET_TABLE        VARCHAR(200),
    EXECUTION_STATUS    VARCHAR(20) DEFAULT 'STARTED', -- STARTED/IN_PROGRESS/SUCCESS/FAILED/PARTIAL
    RECORDS_READ        NUMBER DEFAULT 0,
    RECORDS_INSERTED    NUMBER DEFAULT 0,
    RECORDS_UPDATED     NUMBER DEFAULT 0,
    RECORDS_DELETED     NUMBER DEFAULT 0,
    RECORDS_REJECTED    NUMBER DEFAULT 0,
    RECORDS_SCD2_NEW    NUMBER DEFAULT 0,            -- SCD2 new versions created
    RECORDS_SCD2_CLOSED NUMBER DEFAULT 0,            -- SCD2 records expired
    ERROR_MESSAGE       VARCHAR(4000),
    ERROR_CODE          VARCHAR(50),
    START_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_TIMESTAMP       TIMESTAMP_NTZ,
    DURATION_SECONDS    NUMBER,
    EXECUTED_BY         VARCHAR(100) DEFAULT CURRENT_USER(),
    EXECUTION_WAREHOUSE VARCHAR(100) DEFAULT CURRENT_WAREHOUSE(),
    BATCH_ID            VARCHAR(50),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.PIPELINE_EXECUTION_LOG;
-- ============================================================
-- 2.2 DATA QUALITY ERROR TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.DATA_QUALITY_ERRORS (
    ERROR_ID            VARCHAR(50) DEFAULT UUID_STRING(),
    EXECUTION_ID        VARCHAR(50),
    BATCH_ID            VARCHAR(50),
    SOURCE_TABLE        VARCHAR(200),
    TARGET_TABLE        VARCHAR(200),
    LAYER_NAME          VARCHAR(50),
    ERROR_CATEGORY      VARCHAR(50),    -- SCHEMA/NULL/DATATYPE/RANGE/REFERENTIAL/DUPLICATE/BUSINESS_RULE
    ERROR_SEVERITY      VARCHAR(20),    -- CRITICAL/HIGH/MEDIUM/LOW/WARNING
    COLUMN_NAME         VARCHAR(200),
    ERROR_DESCRIPTION   VARCHAR(4000),
    REJECTED_RECORD     VARIANT,        -- Full record as JSON
    RECORD_IDENTIFIER   VARCHAR(500),   -- Business key of failed record
    RULE_NAME           VARCHAR(200),
    EXPECTED_VALUE      VARCHAR(500),
    ACTUAL_VALUE        VARCHAR(500),
    IS_REPROCESSED      BOOLEAN DEFAULT FALSE,
    REPROCESSED_AT      TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM HOSPITAL_ANALYTICS.AUDIT.DATA_QUALITY_ERRORS;

-- ============================================================
-- 2.3 EXCEPTION HANDLING TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.EXCEPTION_LOG (
    EXCEPTION_ID        VARCHAR(50) DEFAULT UUID_STRING(),
    EXECUTION_ID        VARCHAR(50),
    EXCEPTION_TYPE      VARCHAR(100),   -- SQL_ERROR/TIMEOUT/DEADLOCK/PERMISSION/RESOURCE/CUSTOM
    EXCEPTION_SOURCE    VARCHAR(200),   -- Procedure/Task name
    EXCEPTION_CODE      VARCHAR(50),
    EXCEPTION_STATE     VARCHAR(10),
    EXCEPTION_MESSAGE   VARCHAR(4000),
    STACK_TRACE         VARCHAR(8000),
    SQL_STATEMENT       VARCHAR(8000),  -- The SQL that caused the error
    CONTEXT_INFO        VARIANT,        -- Additional context as JSON
    RETRY_COUNT         NUMBER DEFAULT 0,
    MAX_RETRIES         NUMBER DEFAULT 3,
    IS_RESOLVED         BOOLEAN DEFAULT FALSE,
    RESOLVED_BY         VARCHAR(100),
    RESOLVED_AT         TIMESTAMP_NTZ,
    RESOLUTION_NOTES    VARCHAR(4000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM AUDIT.EXCEPTION_LOG;
-- ============================================================
-- 2.4 FILE INGESTION AUDIT TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.FILE_INGESTION_LOG (
    INGESTION_ID        VARCHAR(50) DEFAULT UUID_STRING(),
    EXECUTION_ID        VARCHAR(50),
    FILE_NAME           VARCHAR(500),
    FILE_PATH           VARCHAR(1000),
    FILE_SIZE_BYTES     NUMBER,
    FILE_FORMAT         VARCHAR(50),
    SOURCE_SYSTEM       VARCHAR(100),
    TABLE_NAME          VARCHAR(200),
    INGESTION_STATUS    VARCHAR(20),     -- SUCCESS/PARTIAL/FAILED/SKIPPED
    ROWS_PARSED         NUMBER DEFAULT 0,
    ROWS_LOADED         NUMBER DEFAULT 0,
    ROWS_ERRORS         NUMBER DEFAULT 0,
    FIRST_ERROR         VARCHAR(4000),
    FIRST_ERROR_LINE    NUMBER,
    FIRST_ERROR_COLUMN  NUMBER,
    FILE_LAST_MODIFIED  TIMESTAMP_NTZ,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM FILE_INGESTION_LOG;
-- ============================================================
-- 2.5 SCD2 AUDIT TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.SCD2_CHANGE_LOG (
    CHANGE_ID           VARCHAR(50) DEFAULT UUID_STRING(),
    EXECUTION_ID        VARCHAR(50),
    TABLE_NAME          VARCHAR(200),
    BUSINESS_KEY        VARCHAR(500),
    CHANGE_TYPE         VARCHAR(20),     -- INSERT/UPDATE/EXPIRE/REACTIVATE
    CHANGED_COLUMNS     VARCHAR(4000),   -- Comma-separated list of changed columns
    OLD_VALUES          VARIANT,         -- Previous values as JSON
    NEW_VALUES          VARIANT,         -- New values as JSON
    OLD_SURROGATE_KEY   VARCHAR(50),
    NEW_SURROGATE_KEY   VARCHAR(50),
    EFFECTIVE_FROM      TIMESTAMP_NTZ,
    EFFECTIVE_TO        TIMESTAMP_NTZ,
    CHANGED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- 2.6 DATA LINEAGE TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.AUDIT.DATA_LINEAGE (
    LINEAGE_ID          VARCHAR(50) DEFAULT UUID_STRING(),
    SOURCE_DATABASE     VARCHAR(100),
    SOURCE_SCHEMA       VARCHAR(100),
    SOURCE_TABLE        VARCHAR(200),
    SOURCE_COLUMN       VARCHAR(200),
    TARGET_DATABASE     VARCHAR(100),
    TARGET_SCHEMA       VARCHAR(100),
    TARGET_TABLE        VARCHAR(200),
    TARGET_COLUMN       VARCHAR(200),
    TRANSFORMATION_LOGIC VARCHAR(4000),
    LAYER_FROM          VARCHAR(50),
    LAYER_TO            VARCHAR(50),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

select * from data_lineage;

-- ============================================================
-- 2.7 CONFIGURATION TABLE
-- ============================================================

CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.CONFIG.PIPELINE_CONFIG (
    CONFIG_ID           NUMBER AUTOINCREMENT,
    TABLE_NAME          VARCHAR(200),
    LAYER_NAME          VARCHAR(50),
    S3_PREFIX           VARCHAR(500),
    FILE_PATTERN        VARCHAR(200),
    LOAD_FREQUENCY      VARCHAR(50),     -- HOURLY/DAILY/WEEKLY
    IS_INCREMENTAL      BOOLEAN DEFAULT FALSE,
    WATERMARK_COLUMN    VARCHAR(200),
    BUSINESS_KEYS       VARCHAR(1000),
    SCD_TYPE            NUMBER,          -- 0/1/2
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    PRIORITY            NUMBER DEFAULT 5,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM CONFIG.PIPELINE_CONFIG;



-- Insert pipeline configurations
INSERT INTO HOSPITAL_ANALYTICS.CONFIG.PIPELINE_CONFIG 
(TABLE_NAME, LAYER_NAME, S3_PREFIX, FILE_PATTERN, LOAD_FREQUENCY, IS_INCREMENTAL, WATERMARK_COLUMN, BUSINESS_KEYS, SCD_TYPE, PRIORITY) 
VALUES
('RAW_PATIENT',        'RAW', 'RAW-PATIENT/',       '.*\\.csv', 'DAILY',  TRUE,  'MODIFIED_DATE', 'PATIENT_ID',     2, 1),
('RAW_DOCTOR',         'RAW', 'RAW-DOCTOR/',        '.*\\.csv', 'DAILY',  TRUE,  'MODIFIED_DATE', 'DOCTOR_ID',      2, 1),
('RAW_ADMISSION',      'RAW', 'RAW-ADMISSION/',     '.*\\.csv', 'HOURLY', TRUE,  'MODIFIED_DATE', 'ADMISSION_ID',   1, 2),
('RAW_OPD_VISIT',      'RAW', 'RAW-OPD-VISIT/',     '.*\\.csv', 'HOURLY', TRUE,  'MODIFIED_DATE', 'VISIT_ID',       1, 2),
('RAW_OPD_DIAGNOSIS',  'RAW', 'RAW-OPD-DIAGNOSIS/', '.*\\.csv', 'HOURLY', TRUE,  'MODIFIED_DATE', 'DIAGNOSIS_ID',   1, 3),
('RAW_LAB_ORDER',      'RAW', 'RAW-LAB-ORDER/',     '.*\\.csv', 'HOURLY', TRUE,  'MODIFIED_DATE', 'LAB_ORDER_ID',   1, 3),
('RAW_TRANSACTION',    'RAW', 'RAW-TRANSACTION/',    '.*\\.csv', 'HOURLY', TRUE,  'MODIFIED_DATE', 'TRANSACTION_ID', 1, 4);


-- Insert lineage once (maps S3 CSV columns → RAW table columns)
INSERT INTO HOSPITAL_ANALYTICS.AUDIT.DATA_LINEAGE
(SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_TABLE, SOURCE_COLUMN,
 TARGET_DATABASE, TARGET_SCHEMA, TARGET_TABLE, TARGET_COLUMN,
 TRANSFORMATION_LOGIC, LAYER_FROM, LAYER_TO)
VALUES
('S3_BUCKET','RAW-ADMISSION','admission.csv','$1','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','ADMISSION_ID','DIRECT_MAP: CSV col 1','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$2','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','PATIENT_ID','DIRECT_MAP: CSV col 2','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$3','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','DOCTOR_ID','DIRECT_MAP: CSV col 3','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$4','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','ADMISSION_DATE','DIRECT_MAP: CSV col 4','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$5','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','DISCHARGE_DATE','DIRECT_MAP: CSV col 5','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$6','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','ADMISSION_TYPE','DIRECT_MAP: CSV col 6','S3','RAW'),
('S3_BUCKET','RAW-ADMISSION','admission.csv','$7','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','WARD_TYPE','DIRECT_MAP: CSV col 7','S3','RAW'),
('SNOWFLAKE','SYSTEM','METADATA','METADATA$FILENAME','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_FILE_NAME','Auto-captured during COPY','S3','RAW'),
('SNOWFLAKE','SYSTEM','METADATA','METADATA$FILE_ROW_NUMBER','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_FILE_ROW','Auto-captured during COPY','S3','RAW'),
('SNOWFLAKE','SYSTEM','FUNCTION','SHA2(all_cols)','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_CHECKSUM','SHA2 hash for change detection','S3','RAW'),
('S3_PATH','PARTITION','year=YYYY','year','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_YEAR','Extracted from S3 folder path','S3','RAW'),
('S3_PATH','PARTITION','month=MM','month','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_MONTH','Extracted from S3 folder path','S3','RAW'),
('S3_PATH','PARTITION','day=DD','day','HOSPITAL_ANALYTICS','RAW','RAW_ADMISSION','_DAY','Extracted from S3 folder path','S3','RAW');