
-- ---------- RAW ADMISSION ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_ADMISSION (
ADMISSION_ID VARCHAR(50),
PATIENT_ID VARCHAR(50),
DOCTOR_ID VARCHAR(50),
ADMISSION_DATE VARCHAR(50),
DISCHARGE_DATE VARCHAR(50),
ADMISSION_TYPE VARCHAR(50), -- EMERGENCY/ELECTIVE/URGENT
WARD_TYPE VARCHAR(50), -- GENERAL/SEMI-PRIVATE/PRIVATE/ICU
ROOM_NUMBER VARCHAR(20),
BED_NUMBER VARCHAR(20),
ADMITTING_DIAGNOSIS VARCHAR(1000),
DISCHARGE_DIAGNOSIS VARCHAR(1000),
DISCHARGE_STATUS VARCHAR(50), -- RECOVERED/TRANSFERRED/DECEASED/LAMA
ATTENDING_DOCTOR_ID VARCHAR(50),
STATUS VARCHAR(20),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);


