----------- RAW OPD VISIT ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_OPD_VISIT (
VISIT_ID VARCHAR(50),
PATIENT_ID VARCHAR(50),
DOCTOR_ID VARCHAR(50),
VISIT_DATE VARCHAR(50),
VISIT_TIME VARCHAR(50),
VISIT_TYPE VARCHAR(50), -- FIRST_VISIT/FOLLOW_UP/REFERRAL
TOKEN_NUMBER VARCHAR(20),
CHIEF_COMPLAINT VARCHAR(1000),
VITALS_BP VARCHAR(20),
VITALS_TEMPERATURE VARCHAR(20),
VITALS_PULSE VARCHAR(20),
VITALS_WEIGHT VARCHAR(20),
VITALS_HEIGHT VARCHAR(20),
VISIT_STATUS VARCHAR(50), -- SCHEDULED/IN_PROGRESS/COMPLETED/CANCELLED/NO_SHOW
NOTES VARCHAR(4000),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);