
-- ---------- RAW DOCTOR ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_DOCTOR (
DOCTOR_ID VARCHAR(50),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
SPECIALIZATION VARCHAR(200),
DEPARTMENT VARCHAR(200),
QUALIFICATION VARCHAR(500),
EXPERIENCE_YEARS VARCHAR(10),
PHONE_NUMBER VARCHAR(20),
EMAIL VARCHAR(200),
CONSULTATION_FEE VARCHAR(20),
AVAILABLE_DAYS VARCHAR(200),
SHIFT_TIMING VARCHAR(100),
LICENSE_NUMBER VARCHAR(50),
JOIN_DATE VARCHAR(50),
STATUS VARCHAR(20),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);