---------- RAW TRANSACTION ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_TRANSACTION (
TRANSACTION_ID VARCHAR(50),
PATIENT_ID VARCHAR(50),
ADMISSION_ID VARCHAR(50),
VISIT_ID VARCHAR(50),
TRANSACTION_DATE VARCHAR(50),
TRANSACTION_TYPE VARCHAR(50), -- CONSULTATION/LAB/PHARMACY/PROCEDURE/ROOM_CHARGE
CHARGE_CODE VARCHAR(50),
DESCRIPTION VARCHAR(500),
QUANTITY VARCHAR(20),
UNIT_PRICE VARCHAR(20),
TOTAL_AMOUNT VARCHAR(20),
DISCOUNT_AMOUNT VARCHAR(20),
TAX_AMOUNT VARCHAR(20),
NET_AMOUNT VARCHAR(20),
PAYMENT_MODE VARCHAR(50), -- CASH/CARD/INSURANCE/UPI/CHEQUE
PAYMENT_STATUS VARCHAR(50), -- PAID/PENDING/PARTIAL/REFUNDED
INSURANCE_CLAIM_ID VARCHAR(50),
INSURANCE_AMOUNT VARCHAR(20),
PATIENT_PAYABLE VARCHAR(20),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);
