- - ============================================================
-- 3.1 RAW TABLES - Exact replica of source + metadata
-- ============================================================


-- ---------- RAW PATIENT ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_PATIENT (
PATIENT_ID VARCHAR(50),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
DATE_OF_BIRTH VARCHAR(50), -- Keep as VARCHAR in RAW
GENDER VARCHAR(20),
BLOOD_GROUP VARCHAR(10),
PHONE_NUMBER VARCHAR(20),
EMAIL VARCHAR(200),
ADDRESS_LINE1 VARCHAR(500),
ADDRESS_LINE2 VARCHAR(500),
CITY VARCHAR(100),
STATE VARCHAR(100),
ZIP_CODE VARCHAR(20),
COUNTRY VARCHAR(100),
EMERGENCY_CONTACT_NAME VARCHAR(200),
EMERGENCY_CONTACT_PHONE VARCHAR(20),
INSURANCE_ID VARCHAR(50),
INSURANCE_PROVIDER VARCHAR(200),
REGISTRATION_DATE VARCHAR(50),
STATUS VARCHAR(20),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata Columns
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64) -- SHA256 for change detection
);
