
---------- RAW LAB ORDER ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_LAB_ORDER (
LAB_ORDER_ID VARCHAR(50),
VISIT_ID VARCHAR(50),
ADMISSION_ID VARCHAR(50),
PATIENT_ID VARCHAR(50),
DOCTOR_ID VARCHAR(50),
TEST_CODE VARCHAR(50),
TEST_NAME VARCHAR(200),
TEST_CATEGORY VARCHAR(100), -- BLOOD/URINE/IMAGING/PATHOLOGY
ORDER_DATE VARCHAR(50),
SAMPLE_COLLECTED_DATE VARCHAR(50),
RESULT_DATE VARCHAR(50),
RESULT_VALUE VARCHAR(200),
RESULT_UNIT VARCHAR(50),
NORMAL_RANGE_LOW VARCHAR(50),
NORMAL_RANGE_HIGH VARCHAR(50),
RESULT_STATUS VARCHAR(50), -- NORMAL/ABNORMAL/CRITICAL
ORDER_STATUS VARCHAR(50), -- ORDERED/SAMPLE_COLLECTED/IN_PROGRESS/COMPLETED/CANCELLED
LAB_TECHNICIAN VARCHAR(100),
NOTES VARCHAR(4000),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);