-- ---------- RAW OPD DIAGNOSIS ----------
CREATE OR REPLACE TABLE HOSPITAL_ANALYTICS.RAW.RAW_OPD_DIAGNOSIS (
DIAGNOSIS_ID VARCHAR(50),
VISIT_ID VARCHAR(50),
PATIENT_ID VARCHAR(50),
DOCTOR_ID VARCHAR(50),
ICD_CODE VARCHAR(20),
DIAGNOSIS_DESCRIPTION VARCHAR(1000),
DIAGNOSIS_TYPE VARCHAR(50), -- PRIMARY/SECONDARY/PROVISIONAL
DIAGNOSIS_DATE VARCHAR(50),
SEVERITY VARCHAR(20), -- MILD/MODERATE/SEVERE/CRITICAL
PRESCRIPTION VARCHAR(4000),
FOLLOW_UP_DATE VARCHAR(50),
NOTES VARCHAR(4000),
MODIFIED_DATE VARCHAR(50),
-- RAW Metadata
_RAW_FILE_NAME VARCHAR(500),
_RAW_FILE_ROW_NUMBER NUMBER,
_RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
_RAW_BATCH_ID VARCHAR(50),
_RAW_SOURCE_SYSTEM VARCHAR(50) DEFAULT 'S3_HOSPITAL',
_RAW_CHECKSUM VARCHAR(64)
);